disquaire_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings

from store import views as store_views

urlpatterns = [
    path('',store_views.IndexView.as_view()),
    path('homesweethome/', admin.site.urls),

    path('store/',include(('store.urls','store'),namespace='store'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append( url(r'^__debug__/', include(debug_toolbar.urls)))

store/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url


urlpatterns = [
    path('listing', views.ListView.as_view(), name='listing'),
    path('detail/<int:id>/',views.detail, name='detail'),
    path('search/', views.search, name='search'),
    
]

store/models.py
from django.db import models

# Create your models here.


class Artist(models.Model):

    name = models.CharField(max_length=200, unique=1)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name="artist"
    

class Contact(models.Model):
    email = models.EmailField(max_length=100)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name="prospect"


class Album(models.Model):
    reference = models.IntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    available = models.BooleanField(default=True)
    title = models.CharField(max_length=200)
    picture = models.URLField()

    artists = models.ManyToManyField(Artist, related_name="albums", blank=1)

    def __str__(self):
        return self.title
    class Meta:
        verbose_name="disque"
    


class Booking(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    contacted = models.BooleanField(default=False)

    album = models.OneToOneField(Album, on_delete=models.CASCADE)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)

    def __str__(self):
        return self.contact.name

    class Meta:
        verbose_name="réservation"
    
    

store/forms.py
from django import forms
from .models import Contact



class ContactForm(forms.ModelForm):

    class Meta:
        model =Contact
        fields = ['name','email']

        widgets = {
            'name': forms.TextInput(),#attrs={'class': 'form-control'}
            'email': forms.EmailInput()
        }
    """
    name = forms.CharField(
        label='Nom',
        max_length=30,
        widget=forms.TextInput(attrs={}),
        required=True 
    )


    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={}),
        required=True)
    """

store/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from . import models

from django.template import loader

from .models import *

from .forms import *

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from django.db import IntegrityError

from django.views import generic

from django.urls import reverse


# Create your views here.


class IndexView(generic.ListView):

    template_name = 'store/index.html'

    context_object_name = 'context'

    def get_queryset(self):

        album_list = Album.objects.filter(available=1).order_by('-created_at')[:12]

        paginator = Paginator(album_list,3)

        page = self.request.GET.get('page')

        try:
            albums = paginator.page(page)
        except PageNotAnInteger:
            albums =paginator.page(1)
        except EmptyPage:
            albums=paginator.page(paginator.num_pages)

        return {'albums':albums,'paginate':True}

class ListView(generic.ListView):

    template_name = 'store/listing.html'
    context_object_name = 'context'

    def get_queryset(self):

        page =self.request.GET.get('page')
        album_list = Album.objects.filter(available=True).order_by('-created_at')

        paginator = Paginator(album_list,3)

        try:
            albums = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            albums = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            albums = paginator.page(paginator.num_pages)

        return {'albums':albums, 'paginate':True}

    #return render(request, 'store/listing.html', {'albums':albums, 'paginate':True})

def detail(request, id):
    album = get_object_or_404(Album, pk=id)
    context = {
        'album_id':album.id,
        'album_title': album.title,
        'artists_name': ' '.join([artist.name for artist in album.artists.all()]),
        'album_id': album.id,
        'thumbnail': album.picture,

        'form': ContactForm()
    }

    if request.method == "POST":
        form = ContactForm(request.POST)
        try:
            if form.is_valid():
                email = request.POST.get("email")
                name = request.POST.get("name")
                album_id = id

                try:
                    contact = Contact.objects.get(email = email)

                except:
                    contact = Contact(name=name.upper(), email=email)

                    contact.save()

                album = get_object_or_404(Album, pk=album_id)
                
                if not album.available:

                    message = "Merci pour l'intérêt mais {} est indisponible".format(album.title)
                else:
                    Booking.objects.create(contact=contact,album=album)

                    #album.available = False

                    album.save()

                    message = "Merci. Vous avez réservé {} avec succès".format(album.title)

                return render(request, 'store/merci.html',{'message':message})

            else:

                context['errors'] = form.errors.items()
                context['form']=form
        except IntegrityError:

            context['internal'] = "Une erreur interne est apparue. Merci de recommencer votre requête."



    
    
    return render(request, 'store/detail.html', context)

    


def search(request):
    query = request.GET.get('query')
    if not query:
        albums = Album.objects.all()
    else:
        albums = Album.objects.filter(title__icontains=query)

        if not albums.exists():
            albums = Album.objects.filter(artists__name__icontains=query)

    title = "Résultats pour la requête %s"%query   

    context ={
        'context':
        {
            'albums' : albums,
            'title' : title
        }
    }

    return render(request, 'store/search.html', context)

store/templates/store/base.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'store/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'store/css/business-casual.css' %}" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="brand"><a href="/">Le bateau pirate</a></div>
    <div class="address-bar">Casque aux oreilles, en route pour Grand line!</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Menu</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Le bateau pirate</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'store:listing' %}">Tous nos disques</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <div class="container">
      <div class="row">
        <div class="box">

        {% block content %}{% endblock %}

        </div>
      </div>
    </div>


    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; <a href="https://samirmaoude.github.io">prototype100500</a></p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'store/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'store/js/bootstrap.min.js' %}"></script>

  </body>
</html>

store/templates/store/detail.html
{% extends 'store/base.html' %}

{% block content %}
<hr>
<h1 class="intro-text text-center">{{ album_title }}</h1>
<hr class="detail-separator">
<div class="col-md-6">
  <img src="{{ thumbnail }}" alt="{{ album_title }}" class="img-responsive">
</div>
<div class="col-md-6">
  <div style="margin-bottom:45px">
    <h2 class="text-center artist_name">Artistes</h2>
    <p>{{ artists_name }}</p>
  </div>

  <h2 class="text-center artist_name">Réserver {{ album_title }}</h2>
  <p style="margin-bottom: 20px;">Demandez-nous de mettre de côté {{ album_title }} et venez le chercher dès demain en magasin ! </p>
  <form class="form-inline" action="{% url 'store:detail' album_id %}" method="post">
    {% csrf_token %}
    <div class="form-group {% if form.name.errors %}has-warning has-feedback{% endif %}">
      <label for="{{form.name.id_for_label}}" class="control-label">Nom</label>
      {{form.name}}
    </div>
    <div class="form-group {% if form.email.errors %}has-warning has-feedback{% endif %}">
      <label for="{{form.email.id_for_label}}" class="control-label">E-mail</label>
      {{form.email}}
    </div>
    <!--<input type="hidden" class="hidden" value="{{ album_id }}" name="album_id">-->

    <button type="submit" class="btn btn-success">Réserver</button>
  </form>

  
  {% if errors %}
    <div>
      {% for key, error in errors %}
      {% autoescape off %}
        {{ error }}
      {% endautoescape %}
      {% endfor %}
    </div>
  {% endif %}

</div>


{% endblock %}

store/templates/store/index.html
{% extends 'store/base.html' %}


{% block content %}

{% include 'store/list.html' with list_title='Nos albums' %}

{% endblock %}

store/templates/store/list.html
<div class="col-lg-12">
    <hr>
    <h2 class="intro-text text-center">{{ list_title }}
    </h2>
    <hr class="detail-separator">
</div>

{% include 'store/search_form.html' %} <!-- NEW -->

{% if context.albums|length_is:"0" %}
    <div class="text-center">
      Palsambleu ! Nous n'avons trouvé aucun résultat à cette requête. Même pas de quoi se ronger la chique !
      Partez de nouveau à l'abordage !
    </div>

{% else %}

    {% for album in context.albums %}
        <div class="col-sm-4 text-center">
            <a href="{% url 'store:detail' album.id %}">
            <img class="img-responsive" src="{{ album.picture }}" alt="{{ album.title }} height="352" width="470" ">
            </a>
            <h3><a href="/">{{ album.title }}</a></h3>
            {% for artist in album.artists.all %}
                <p>{{ artist.name }}</p>
            {% endfor %}
        </div>
        {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}
    {% endfor %}
    {% if context.paginate %}
        <div class="clearfix"></div>
        <nav aria-label="...">
            <ul class="pager">
            {% if context.albums.has_previous %}
                <li><a href="?page={{ context.albums.previous_page_number }}">Précédent</a></li>
            {% endif %}
            {% if context.albums.has_next %}
                <li><a href="?page={{ context.albums.next_page_number }}">Suivant</a></li>
            {% endif %}
            </ul>
        </nav>
    {% endif %}

{% endif %}

  

store/templates/store/listing.html
{% extends 'store/base.html' %}


{% block content %}

    {% include 'store/list.html' with list_title='Tous nos disques' %}

{% endblock %}

store/templates/store/merci.html
{% extends 'store/base.html' %}


{% block content %}
    <hr>
    <h1 class="intro-text text-center">Merci !</h1>
    <hr class="detail-separator">
    <p>{{ message }}<p/>

{% endblock %}

store/templates/store/search.html
{% extends 'store/base.html' %}


{% block content %}

    {% include 'store/list.html' with list_title=context.title %}

{% endblock %}

store/templates/store/search_form.html
<div class="col-lg-12 detail-separator">
  <form class="col-md-6 col-md-offset-3 text-center" action="{% url 'store:search' %}" method="get" accept-charset="utf-8">
    <div class="form-group">
      <label for="searchForm">Chercher un disque</label>
      <input id="searchForm" class="form-control" name="query">
    </div>
    <span class="help-block" id="helpBlock">Trouvez le CD de vos rêves en tapant son titre ou le nom d'un des artistes.</span>
  </form>
</div>